version: '3.8'
services:
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: ./packages/backend
    ports:
      - "3001:3001"
